---
dependency:
  name: galaxy
driver:
  name: docker
  options:
    D: true
    vv: true
lint: |
  yamllint .
  ansible-lint .
  flake8
platforms:
  - name: centos_7
    image: dokken/centos-7:latest
    #pre_build_image: true
    dockerfile: ../resources/Dockerfile.j2
    command: /usr/sbin/init
    privileged: true
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    env:
      ANSIBLE_USER: ansible
      SUDO_GROUP: wheel
      DEPLOY_GROUP: deployer
      container: docker
  - name: centos_8
    image: dokken/centos-8:latest
    #pre_build_image: true    
    dockerfile: ../resources/Dockerfile.j2
    command: /usr/sbin/init
    privileged: true
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    env:
      ANSIBLE_USER: ansible
      SUDO_GROUP: wheel
      DEPLOY_GROUP: deployer
      container: docker
  - name: almalinux_8
    image: dokken/almalinux-8:latest
    #pre_build_image: true
    dockerfile: ../resources/Dockerfile.j2
    command: /usr/sbin/init
    privileged: true
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    env:
      ANSIBLE_USER: ansible
      SUDO_GROUP: wheel
      DEPLOY_GROUP: deployer
      container: docker
provisioner:
  name: ansible
  options:
    vv: true
    D: true
verifier:
  name: ansible
